export const TYPES = {
  INCREMENT_BREAK: 'INCREMENT_BREAK',
  DECREMENT_BREAK: 'DECREMENT_BREAK',
  INCREMENT_SESSION: 'INCREMENT_SESSION',
  DECREMENT_SESSION: 'DECREMENT_SESSION',

  UPDATE_TIMER_MINUTE: 'UPDATE_TIMER_MINUTE',
  DEC_SECONDS: 'DEC_SECONDS',

  SWITCH_SESSION: 'SWITCH_SESSION',
  SWITCH_BREAK: 'SWITCH_BREAK',

  START_TIMER: 'START_TIMER',
  STOP_TIMER: 'STOP_TIMER',
  RESET_TIMER: 'RESET_TIMER',
};